[theme]
base                   = "dark"
primaryColor           = "#00cc66"
backgroundColor        = "#0e1210"
secondaryBackgroundColor = "#161e18"
textColor              = "#f0fff6"
font                   = "sans serif"
